### PR TITLE
Making workflow changes to support deployment as per 14.4.6 version

### PR DESCRIPTION
**Pull request by rajpalc7**

### CODE REVIEW

**Comment by WadeBarnes** [comment]
@esune, @rajpalc7, I think we should have a meeting to review this thoroughly together.  I'm also thinking we need some documentation on the setup and debugging process so we have that for reference if things ever stop working again.

**Comment by WadeBarnes** [comment]
@rajpalc7, @esune, Is there an issue tracking the work here that we could link to?

**Comment by esune** [comment]
> @rajpalc7, @esune, Is there an issue tracking the work here that we could link to?

No, we do not have one - we can log on

> @rajpalc7, @esune, Is there an issue tracking the work here that we could link to?

No, we do not have an issue - this was generated by @rajpalc7 investigating something else. We should probably  log one on this repo, I guess.

**Comment by WadeBarnes** [comment]
Added myself as an assignee for tracking purposes.

**Review by WadeBarnes — CHANGES_REQUESTED** [review]
@rajpalc7, Could you move the documentation up to where it has more context please.

I expected this;
image
to be placed in this section;
image
to document why the change was relevant.

**Comment by rajpalc7** [comment]
Thank you @WadeBarnes I have moved the comments as per your suggestion.

**Review by WadeBarnes — APPROVED** [review]

**Pull request merged**
