### PR TITLE
Feat/build

### PR DESCRIPTION
**Pull request by rajpalc7**

### CODE REVIEW

**Review by WadeBarnes — CHANGES_REQUESTED** [review]
Looking good @rajpalc7.  There are a few cleanup items I've noted as `ToDo`s in the workflow.

I'd like to start out by refactoring the deployment jobs into a reusable workflow since the steps are basically identical.  Let me know when you have some time and we can walk through that together.  From there we'll decide which `ToDo` to tackle next.

**Comment by WadeBarnes** [comment]
@rajpalc7, I've also rebased your commits to clear up some changes that shouldn't have been included in the PR.  You might need to reset your working copy to the latest commits on the `feat/build` branch before you continue development.  We can review that together when we look at the reusable workflow.

**Comment by WadeBarnes** [comment]
@rajpalc7, slight change in plan.  I had a quick chat with @cvarjao and we agreed we should clean up and merge this PR before making any enhancements.  I'll work on that and I'll create the tickets describing the further enhancements separately.

**Review by WadeBarnes — APPROVED** [review]

**Comment by rajpalc7** [comment]
Sounds good Wade, I like the latest plan as this will let me focus on the current sprint tickets and other outstanding tasks.

**Pull request merged**
